### ISSUE TITLE
Documentation about installation is incomplete

### ISSUE THREAD

**Issue by dschrempf** [skarra/ASynK#108]
Hello,

installation of ASynK was not clear to me.  The documentation on the homepage and on the GitHub repository do not state that `git submodule update --init --recursive` also needs to be run for a new install, not only for an update.  In retrospect this is clear but initially, I was not aware that ASynK uses submodules and execution provided me with very obscure error messages.

**Comment by skarra** [comment]
The documentation did mention the use of --recursive flag for clone; but I
have not made it a little more obvious. via
https://github.com/skarra/ASynK/commit/1ce7c43d975e312681742651b79b76756638e532
