### ISSUE TITLE
Unknown date format

### ISSUE THREAD

**Issue by dschrempf** [skarra/ASynK#110]
I am trying to sync with Nextcloud.  It seems to save time stamps in the following format:

    20161212T112613

This format cannot be read by ASynK and the following error is thrown:

      File "/home/dominik/Shared/aur/ASynK/lib/iso8601.py", line 22, in parse
        raise ValueError, "unknown or illegal ISO-8601 date format: " + `s`
    ValueError: unknown or illegal ISO-8601 date format: u'20161212T112613'

**Comment by skarra** [comment]
As far as I can see, the format is not valid ISO format. Can you file a bug with Nextcloud and see what they say? The format is missing at least a "Z" at the end. ASynK uses a version of the iso8601 parser written by Fred Drake...

**Comment by skarra** [comment]
I take that back. Can you try this branch and see if it fixes the issue for you? https://github.com/skarra/ASynK/tree/issues/110

**Comment by skarra** [comment]
I have merged this to master and deleted the branch.
