### ISSUE TITLE
vobject not defined

### ISSUE THREAD

**Issue by nico202** [skarra/ASynK#113]
Hi, I have problem using asynk. it can import vobject, but fails at that line:

  File "/nix/store/1i2jss4x1wb9xzh3m0w73s7djj8y3v92-ASynK-2.2.0/asynk/folder_cd.py", line 182, in find_items
    cd = CDContact(self, vco=vobject.readOne(vcf.text), itemid=key)
NameError: global name 'vobject' is not defined

**Comment by skarra** [comment]
This indicates the submodues are not updated. Can you do a recursive pull / udpate?
