### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by schvabodka-man** [skarra/ASynK#118]
Trying to run this(creating new profile) and getting some simple library import error

```
Traceback (most recent call last):
  File "asynk.py", line 30, in <module>
    from   asynk_core       import Asynk, AsynkParserError
  File "/home/user/Test/ASynK/asynk/asynk_core.py", line 40, in <module>
    from   sync             import Sync
  File "/home/user/Test/ASynK/asynk/sync.py", line 28, in <module>
    import atom, gdata
ImportError: No module named atom
```

**Comment by schvabodka-man** [comment]
Ok, the trouble was deps. Why the hell there are no atom, gdata, pyload and other stuff in requirements.txt?

And now i'm getting this one

```
Traceback (most recent call last):
  File "asynk.py", line 30, in <module>
    from   asynk_core       import Asynk, AsynkParserError
  File "/home/user/Test/ASynK/asynk/asynk_core.py", line 40, in <module>
    from   sync             import Sync
  File "/home/user/Test/ASynK/asynk/sync.py", line 28, in <module>
    import atom, gdata
  File "/usr/lib/python2.7/site-packages/gdata/__init__.py", line 109, in <module>
    class LinkFinder(atom.LinkFinder):
AttributeError: 'module' object has no attribute 'LinkFinder'

```

**Comment by skarra** [comment]
Because some of them area distributed as sub-modules...?

Did you do this, as recommended in the README file?

```
git clone  --recursive https://github.com/skarra/ASynK.git
```

**Comment by schvabodka-man** [comment]
Yes, i did this. I cloned recursively, not with regular clone. A also runned setup.py both for build and install. I also installed parser wrapper library from repo

**Comment by skarra** [comment]
Actually both atom and gdata are in the libs/ subdirectory, so you should not be hitting this problem at all.

How did you invoke asynk?

**Comment by schvabodka-man** [comment]
Yes, the're in lib directory. I run it like this

python asynk.py --op=create-profile --name bbdb --user-dir=somecfgdir --db bb cd --folder default default --store somepath someip:someip --cduser=someuser

Also, anyway, if i run python asynk.py i get this error

**Comment by skarra** [comment]
I am not able to reproduce the problem. I suggest do the following to see if it has something to do with your python library path or something.

```
1. install a new virtualenv and activate it
2. git clone --recursive https://github.com/skarra/ASynK
3. cd ASynK && pip install -r requirements.txt
4. python asynk.py --version
```
