### ISSUE TITLE
New error syncing between gc and bb: "Exception AttributeError: "'GCPIMDB' object has no attribute 'server'"

### ISSUE THREAD

**Issue by dinojr** [skarra/ASynK#128]
I'm running the head of master git. Today, syncing bb and gc failed with:

Exception AttributeError: "'GCPIMDB' object has no attribute 'server'" in <bound method GCPIMDB.__del__ of <pimdb_gc.GCPIMDB object at 0x7f39c17baf90>> ignored

**Comment by skarra** [comment]
Can you check the debug logs file in the ~/.asynk/logs/ directory to see if there is a stack trace or a line number?

Also this looks suspiciously similar to the problem that was fixed by this commit: 0582aef285788be24d8ffeafb65cc0fa833df3bd, so can you double check if you are up to date?

**Comment by dinojr** [comment]
Turns out my local version (installed by pip) of httplib2 was out of date. Upgrading it solved the issue.
