### ISSUE TITLE
Could not parse BBDB record

### ISSUE THREAD

**Issue by moy** [skarra/ASynK#35]
I'm using BBDB 3, but my ~/.bbdb was converted from BBDB 2. I seem to get "Could not parse BBDB record" for most records in my file. Here's one of them:

["promo telecom" "2A" nil nil ("ENSIMAG") nil nil ("telecom2a@ensimag.imag.fr") ((creation-date . "2002-01-07") (timestamp . "2002-01-07") (mail-alias . "telecom2a")) nil]

**Comment by skarra** [comment]
Will track this via other linked issue.
