### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'authenticators'

### ISSUE THREAD

**Issue by magnific0** [skarra/ASynK#56]
When I try to run an list_folders or sync operation, I get an error. Running ```asynk.py```, ```asynk.py -h```, or ```asynk.py -op=create-profile …``` does **not** produce any errors.

My python version is 2.7.9. Cleaning the configuration and running

    python2.7 asynk.py --op=sync --dry-run

produces:

    Traceback (most recent call last):
    File "asynk.py", line 302, in <module>
        main()
    File "asynk.py", line 299, in main
        asynk.dispatch()
    File "/home/user/Gits/ASynK/asynk/asynk_core.py", line 97, in dispatch
        res = getattr(self, self.get_op())()
    File "/home/user/Gits/ASynK/asynk/asynk_core.py", line 116, in op_list_folders
        self._login()
    File "/home/user/Gits/ASynK/asynk/asynk_core.py", line 84, in _login
        coll.init_username_pwd()
    File "/home/user/Gits/ASynK/asynk/state_collection.py", line 214, in init_username_pwd
        self.get_colln())
    File "/home/user/Gits/ASynK/asynk/state_collection.py", line 65, in get_auth
        res = self.netrc.authenticators(mach)
    AttributeError: 'NoneType' object has no attribute 'authenticators'

Do you have any idea what might be causing this? Are there any addiotional tests I could perform?

**Comment by skarra** [comment]
What is the version of asynk you are using?

**Comment by skarra** [comment]
Ah, I see... a fix for this is in ```gae``` branch. Can you apply the following patch to get you gonig?

```
diff --git a/asynk/state_collection.py b/asynk/state_collection.py
index 12c24a2..db04a9f 100644
--- a/asynk/state_collection.py
+++ b/asynk/state_collection.py
@@ -60,6 +60,9 @@ class NetrcAuth:
         how to use the coll_n parameter and should expect that parameter to be
         ignored if that suits the netrc data!"""
 
+        if self.netrc is None:
+            return None, None
+
         tries = ['%s%s_%s' % (dbid, coll_n, pname), '%s_%s' % (dbid, pname)]
         for mach in tries:
             res = self.netrc.authenticators(mach)
```

**Comment by skarra** [comment]
I have pushed the above commit to master. You can just pull latest

**Comment by magnific0** [comment]
Hi skarra, I couldn't test things before, but this fixed it for me. Everything is working great now, thanks!

**Comment by skarra** [comment]
Awesome, glad it worked.
