### ISSUE TITLE
do first default sync with Google, delete .bbdb file, resync deletes all Google contacts

### ISSUE THREAD

**Issue by bradyt** [skarra/ASynK#57]
Hi, experimenting, I decided to remove .bbdb after my first test sync to see what would happen. 

A subsequent sync deleted all contacts in Google, as deleted .bbdb is "newer".

**Comment by skarra** [comment]
What you have explained is the expected behaviour. I am not sure I understand what you would like it to be. Are you looking to restore you gmail contacts?

**Comment by bradyt** [comment]
No restore needed, just confirming behavior.

**Comment by skarra** [comment]
cool
