### ISSUE TITLE
Old CalDAV library

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#60]
AsynK uses [CalDAVClientLibrary](http://trac.calendarserver.org/wiki/CalDAVClientLibrary) which seems unmaintained. It looks like there are alternative ones: http://caldav.calconnect.org/implementations/librariestools.html

**Comment by skarra** [comment]
The last commit to that SVN repo was in April 2015. Why do you say it is unmaintained?

```
Srirams-MacBook-Pro:CalDAVClientLibrary sriramkarra$ svn log | head
------------------------------------------------------------------------
r14670 | cdaboo@apple.com | 2015-04-10 00:14:22 +0530 (Fri, 10 Apr 2015) | 2 lines

Commands for calendar trash manipulation.

------------------------------------------------------------------------
r14596 | cdaboo@apple.com | 2015-03-16 06:00:29 +0530 (Mon, 16 Mar 2015) | 2 lines

Some servers now require a User-Agent.
```

**Comment by DamienCassou** [comment]
You are right sorry. Your fork is 2 years old though. Is there a reason to keep an old version?

**Comment by skarra** [comment]
I had contributed a number of patches to upstream. Just not found the time to properly rebase my changes on top of latest. One of these days ...
