### ISSUE TITLE
Separate private data and configuration

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#62]
Hi,

it looks like `~/.asynk/state.json` serves both as asynk private data store (e.g., for `last_sync_start` and `items`) and as user-configuration file (e.g., for `default_profile` and `profiles`). This is bad because (1) it clutters user files with implementation details user won't understand and (2) it clutters the revision control system of the user with commits users should not care about.

**Comment by skarra** [comment]
I do not agree that ```default_profile``` and list of profiles is user config. It is application state (i.e. which is read-write for the asynk application), and different from application configuration which lives in ~/.asynk/config.py (which is read-only for the asynk application)

So yes I acknowledge the distinction you are driving at here, and I have already taken the effort to separate them out. Users should really not need to look inside state.json at all.

**Comment by DamienCassou** [comment]
Thanks for the explanation
