### ISSUE TITLE
vCard folder sync?

### ISSUE THREAD

**Issue by retorquere** [skarra/ASynK#67]
Would it be possible to add sync from/to a folder of vCard files? I tried to go it my own, but my python-fu is weak.

**Comment by skarra** [comment]
You mean sync from a folder in a Unix folder (or similar) to another folder on the same machine or somewhere else? I am not sure it would be worth the trouble supporting that in ASynK as a two step rsync can do almost do a similar thing, right?

**Comment by retorquere** [comment]
Right, but that's not what I meant; I want to sync between a folder of vCard files and a Google Contacts group.

**Comment by skarra** [comment]
Ah, it could certainly be done, but I do not have the bandwidth at the moment.

**Comment by skarra** [comment]
How do you process your vCard folder?

**Comment by retorquere** [comment]
By a ruby script. I don't even particularly care about vcard - I just need
a way to sync stuff to google contacts, and I don't understand the bbdb
format. If I understood the format, I could generate that.

**Comment by skarra** [comment]
Can you explain your use case a little more? Like:

- Do you have contact info today that you would like to sync to Google?, or
- Do you have contacts in Google Contacts you want to backup?
- Do you need bi-directional sync - i.e. do you edit contacts in both locations?

**Comment by retorquere** [comment]
I've since found another way of doing what I want, but my use case was:

I have a script that downloads the Global Address List (in fact the Offline Address Book to be exact) from an Exchange server. I want to sync that list into a Google Contacts group, so that I have caller ID for office numbers. The sync I perform currently works as follows:

Get Exchange OAB, and for each entry therein I find a corresponding entry in Google Contacts, matching on email address. If the OAB entry has no email, I skip it.

If no corresponding entry is found: create a new contact from the OAB entry, and add it to the "Coworkers" group

If a corresponding entry is found:
* remove all telephone numbers from the Contacts entry that are:
  * labelled "Work",
  * labelled "Work Mobile", or
  * occur in the OAB contact
* add all telephone numbers in the OAB contact and label them "Work" or "Work Mobile" as appropriate
* add the GContact to the "Coworkers" group

This way, I can add phone numbers not listed in the OAB (personal numbers, work numbers that haven't yet made it into the GAL) without them being lost on sync.

**Comment by skarra** [comment]
YA sort of complex workflow :)

BTW - ASynK supports Exchange Server natively. Did you give that a shot? i am currently having oAuth trouble with Google, but you can sync Exchange to a local directory or CardDAV server.

**Comment by retorquere** [comment]
I haven't tried the Exchange sync, but I would venture to guess it's reading the personal contacts, where I was specifically looking for the GAL. Reading the GAL is a bit involved, but I got it working with some help from the great folks from eM Client.

**Comment by retorquere** [comment]
Oh and the original workflow was substantially simpler -- a one-way sync from GAL to Coworkers.
