### ISSUE TITLE
Updates to contacts in Fastmail Addressbook are not being picked up

### ISSUE THREAD

**Issue by skarra** [skarra/ASynK#72]
This is actually due to a bug in Fastmail's implementaiton.

Editing a contact using Fastmail's web interface to the addressbook is not updating the REV field. For e.g. the following is a contact I wrote to my Fastmail addressbook using ASynK at around 10am UTC today. I just edited its notes field just now (around 2pm UTC), and performed a sync dry run using ASynK. The changes to the contact I made are visible but the REV has not been updated and as a result it is not being picked up as a modified contact. 

This needs to be fixed by Fastmail. @duncan-bayne you may want to highlight this issue with your Fastmail support contact.

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//ASynK v2.1.0-rc2+//EN
UID:1795e445-127f-11e5-b948-20c9d0851eb3
FN:Dr. Narayananaya Namo
N:Namo;Narayananaya;;Dr.;
NICKNAME:Nannu
NOTE:Updating the notes at approx 2pm UTC
REV:20150614T102117Z
X-ASYNK-CREATED:20150614T102117Z
X-ASYNK-SYNCTAG-FASTMAILBB-BB:cc00ed7a-9fde-11e4-aaf5-20c9d0851eb3
END:VCARD
```

**Comment by skarra** [comment]
I have raised ticket number: 779537 with Fastmail support for this issue.

**Comment by duncan-bayne** [comment]
@skarra I've brought it to their attention too, I'll let you know when I get a reply.

**Comment by skarra** [comment]
Cool; this only affects fetching updates on Fastmail. The other dirction should still be fine right now. Give that a shot now.

**Comment by duncan-bayne** [comment]
I just did - it got most of the way through then fell over on one particular VCF.

**Comment by duncan-bayne** [comment]
Fastmail support replied to say that this has been escalated to their dev team.

**Comment by brong** [comment]
Hi from FastMail :)

I'm testing a patch for this now.

**Comment by brong** [comment]
UID:11594008-a4e2-4d71-adb4-3804f4d22638
FN:A NEW Contact
ORG:;;
NOTE:
N:Contact;A NEW;;
NICKNAME:
REV:20150616T055123Z

...

UID:11594008-a4e2-4d71-adb4-3804f4d22638
FN:A NEW Contact
ORG:;;
NOTE:
N:Contact;A NEW;;
NICKNAME:
REV:20150616T055240Z
EMAIL;TYPE=personal;TYPE=pref:test@example.com

Looking good :)

**Comment by duncan-bayne** [comment]
This is one of the reasons I'm a) very happy to pay money for Fastmail, and b) tirelessly evangelise Fastmail to my family, friends and colleagues :+1:

**Comment by skarra** [comment]
@brong thanks for taking a look at this.

I am still not seeing the updated timestamp. Just updated a contact's notes and personal email field. I am seeing updates to the actual fields below, but the timestamp is still 2 days old.

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//ASynK v2.1.0-rc2+//EN
UID:1795e445-127f-11e5-b948-20c9d0851eb3
EMAIL;TYPE=personal,pref:test@mailinator.com
FN:Dr. Narayananaya Namo
N:Namo;Narayananaya;;Dr.;
NICKNAME:Nannu
NOTE:Updating the notes at approx 06:30 UTC
REV:20150614T102117Z
TEL;TYPE=cell:+91 90084 88997
X-ASYNK-CREATED:20150614T102117Z
X-ASYNK-SYNCTAG-FASTMAILBB-BB:cc00ed7a-9fde-11e4-aaf5-20c9d0851eb3
END:VCARD
```

**Comment by brong** [comment]
Yeah, that's just my testing server - it's not going out to production servers at 3:45pm on a day when I'm busy all evening - not fair to the on-call.  Plus I have some much more "dangerous" changes in QA right now, and I'd rather not confuse matters by pushing another change into the QA pipeline while the tests are still ongoing (these changes are pretty much a rewrite of the mailbox listing code - it's about the most hairy bit, and despite having almost the best test coverage of anything and passing those tests, I want real-world client tests as well, and that takes time)

I'll come back and update this issue (and the two support tickets) once I have rolled out the change everywhere - hopefully tomorrow unless something big blocks me.

**Comment by skarra** [comment]
Sound good and reasonable. I did see your comments on the support ticket I had raised, but I took your comments here to mean you had pushed the code out.

Thanks for jumping on this. Really appreciate it.

**Comment by brong** [comment]
FYI - this went into production some time in the past couple of days, depending which server you were on.  It's fully deployed now, so all good for everyone.

Do feel free to open new tickets if you find any other problems with our DAV support - we want to have the best possible product, so bug reports are grealy appreciated.

Regards,

Bron.

**Comment by skarra** [comment]
Awesome, I can confirm that the issue is fixed.
