### ISSUE TITLE
gdata.client.Unauthorized: Unauthorized - Server responded with: 401

### ISSUE THREAD

**Issue by zvonko123** [skarra/ASynK#73]
This is what happens when u try to use the **saved credentials** for GC (the .dat file in the specified --user-dir argument) after it expires. after that, u have to manually remove the <login@domain.com.dat> file and click (authorize) the app again in the browser (curl) after re-running the script

Could it be done so u really have to **click only once**, like it says in the new readme ?

<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>authError</code>
  <location type="header">Authorization</location>
  <internalReason>Invalid Credentials</internalReason>
 </error>
</errors>

**Comment by skarra** [comment]
It's possible; but I do not have time to look into it now

**Comment by skarra** [comment]
Now fixed in master via: https://github.com/skarra/ASynK/commit/1a1d0092cdbecf195b45fb5cdf6435d1dfad90f2
