### ISSUE TITLE
del_itemids method in asynk/folder_cd.py

### ISSUE THREAD

**Issue by zvonko123** [skarra/ASynK#74]
[Link to troubling code](https://github.com/skarra/ASynK/blob/master/asynk/folder_cd.py#L133)

this line makes me curious, as the itemids list is just hashes and not links.

when u call URL(itemid), the hash is lost and u get an empty URL object i guess

this is why your delete method doesnt work for CarDav (faulty url)

can u explain ?

**Comment by skarra** [comment]
Excellent catch. In the original implementation itemids were full paths of the resource. There were various issues with that approach, and I changed that via: 18f0f58dff1e45074a1fac7dfd641f546c65d14d but this got left behind. Will look into this.

**Comment by skarra** [comment]
Can you check now?

**Comment by zvonko123** [comment]
Its better but the itemids are wrong for some reason.
(are 90% identical but in the end of the string instead of 25250localhost it writes it as 2525250localhost, so it adds an additional '25" in the string

trying to investigate

**Comment by skarra** [comment]
I am able to successfully process deletes on my local Baikal CardDAV server. I am not sure what problem you are seeing. Let me know what you find.

**Comment by zvonko123** [comment]
ok i was using owncloud, trying with baikal now.

sync order in state.json is GC is coll1 and CD is coll2.

so i added 3 contacts to gmail, running sync once PUTs them in Baikal,
but running the script again puts the same 3 contacts AGAIN, although no user changes were made (via the UI)
so every subsequent run just adds the contacts again in spite the fact they were added already..

**Comment by skarra** [comment]
That is a different issue; moving discussion to: https://github.com/skarra/ASynK/issues/75
