### ISSUE TITLE
GC -> Baikal sync duplicates entry on re-run

### ISSUE THREAD

**Issue by skarra** [skarra/ASynK#75]
Report from user:

sync order in state.json is GC is coll1 and CD is coll2.

so i added 3 contacts to gmail, running sync once PUTs them in Baikal,
but running the script again puts the same 3 contacts AGAIN, although no user changes were made (via the UI)

so every subsequent run just adds the contacts again in spite the fact they were added already..

**Comment by zvonko123** [comment]
Tried reversing so GC is coll2 and CD is coll1, the bug doesnt appear in this way.

But when i delete a contact in GC via the gmail UI, and run the script again, it doesnt send a DELETE request to carddav, although it lists 1 contact less and it should delete it

Is this a logical flaw in the code? I figure the CD part of syncing isnt really complete ?

**Comment by skarra** [comment]
Can you send me the output of ```asynk.py --op=show-profile --name=<your profile>```

**Comment by zvonko123** [comment]
./asynk.py --op=show-profile --name=testgccd
Applying base config from file /home/***/workspace/python/ASynK/config/config_v7.json...
Applying base config from file /home/***/workspace/python/ASynK/config/config_v7.json...done
Applying user customizations from file /home/***/.asynk/config.py...
Applying user customizations from file /home/***/.asynk/config.py...done
INFO:root:Debug logging to file: /home/***/.asynk/logs/asynk_logs.2015-07-02.14-27-54.989564
[14:27:54.989     INFO] Debug logging to file: /home/***/.asynk/logs/asynk_logs.2015-07-02.14-27-54.989564
DEBUG:root:Command line: "./asynk.py --op=show-profile --name=testgccd"
INFO:root:Deleting log files older than 7 days, if any...
[14:27:54.991     INFO] Deleting log files older than 7 days, if any...
INFO:root:Deleting log files older than 7 days, if any...done
[14:27:54.991     INFO] Deleting log files older than 7 days, if any...done
INFO:root:*** Profile   : testgccd ***
[14:27:54.992     INFO] *** Profile   : testgccd ***
INFO:root:  Collection 1: 
[14:27:54.992     INFO]   Collection 1: 
INFO:root:    DB ID     : cd
[14:27:54.992     INFO]     DB ID     : cd
INFO:root:    Store ID  : http://localhost/baikal-flat/card.php
[14:27:54.992     INFO]     Store ID  : http://localhost/baikal-flat/card.php
INFO:root:    Folder ID : default
[14:27:54.993     INFO]     Folder ID : default
INFO:root:  Collection 2: 
[14:27:54.993     INFO]   Collection 2: 
INFO:root:    DB ID     : gc
[14:27:54.993     INFO]     DB ID     : gc
INFO:root:    Store ID  : None
[14:27:54.993     INFO]     Store ID  : None
INFO:root:    Folder ID : default
[14:27:54.994     INFO]     Folder ID : default
INFO:root:  sync_start  : 2015-07-02T10:47:14.09Z
[14:27:54.994     INFO]   sync_start  : 2015-07-02T10:47:14.09Z
INFO:root:  sync_stop   : 2015-07-02T10:47:15.39Z
[14:27:54.994     INFO]   sync_stop   : 2015-07-02T10:47:15.39Z
INFO:root:  sync_dir    : SYNC2WAY
[14:27:54.995     INFO]   sync_dir    : SYNC2WAY
INFO:root:  confl_res   : gc
[14:27:54.995     INFO]   confl_res   : gc
INFO:root:  olgid       : 0x0
[14:27:54.995     INFO]   olgid       : 0x0

**Comment by skarra** [comment]
I am not able to reproduce this problem. Can you email me your logs from ~/.asynk/logs directory for the run *before* the run when they actually got duplicated?

**Comment by zvonko123** [comment]
as i said, the duplicating doesnt appear if i reverse them,

but what about delete requests, obviously i deleted contacts from GC and it doesnt update the deleted ones to CD. coll1 is CD..

**Comment by skarra** [comment]
Well, in your original report you said coll1:coll2::gc:cd is the problem. I tried that configuration and not able to reproduce. 

Now you saying coll1:coll2::cd:gc is the problem. I tried it just now, and still not able to reproduce it. Can you show some more debug logs? I cannot debug this any more without more logs.

**Comment by skarra** [comment]
To be clear - with both settings I created a contact in GC, synched it to Baikal, then deleted it in GC, and then synched it to Baikal (it was successfully deleted).

**Comment by skarra** [comment]
There is a sort of unrelated bug fix in a branch called gcbug. Can you try that if you are still running into this issue?

**Comment by zvonko123** [comment]
i dont see a branch with the name gcbug

**Comment by skarra** [comment]
Sorry, it was a local branch.I just merged to master and pushed. Please update to latest.

**Comment by skarra** [comment]
As debugged offline, this was not due to an issue with ASynK, but due to a  spurious quote character in the GC feed - something I am not able to explain; but the submitter has fixed it and "happy"
