### ISSUE TITLE
'Error: Code: 405, Reason: Method Not Allowed' synchronising with Fastmail

### ISSUE THREAD

**Issue by duncan-bayne** [skarra/ASynK#77]
When synchronising with Fastmail CardDAV, I'm getting the following error:

```
[06:33:28.017     INFO] Logging into CardDAV server: https://carddav.messagingengine.com/dav/ad - user: duncan@bayne.id.au...
DEBUG:root:PIMDB cd does not have email_domains.
DEBUG:root:PIMDB cd does not have postal_map
DEBUG:root:PIMDB cd does not have notes_map
DEBUG:root:PIMDB cd does not have phones_map
DEBUG:root:Sending request OPTIONS to server carddav.messagingengine.com/dav/ad...
DEBUG:root:Sending Request URL: /dav/ad Method: OPTIONS
DEBUG:root:Received Response: HTTP/1.1 401 Unauthorized

DEBUG:root:Sending request OPTIONS to server carddav.messagingengine.com/dav/ad...
DEBUG:root:Sending Request URL: /dav/ad Method: OPTIONS
DEBUG:root:Received Response: HTTP/1.1 200 OK

DEBUG:root:Sending Request URL: /dav/ad Method: PROPFIND
DEBUG:root:Received Response: HTTP/1.1 405 Method Not Allowed

CRITICAL:root:Could not open connection to Carddav Server (https://carddav.messagingengine.com). Error: Code: 405, Reason: Method Not Allowed
[06:33:31.191 CRITICAL] Could not open connection to Carddav Server (https://carddav.messagingengine.com). Error: Code: 405, Reason: Method Not Allowed
```

This used to work; I've recently reinstalled my system and installed the latest ASynK from master.

If this is an issue on Fastmail's side I'm happy to raise a support ticket with them, as they were very responsive last time.

**Comment by skarra** [comment]
Hm, it is possible it was a change at Fastmail's end. But I would like you to check one thing before that - your stid parameter looks a bit suspect. The URL that works for me looks something like this: /dav/addressbooks/user/abcd%40fastmail.com/

In your logs the domain part is missing. Can you edit your ~/.asynk/state.json to make that your full qualified email address and then try again?

**Comment by duncan-bayne** [comment]
Really weird - I recreated it, and it worked fine.  I assume there's a bug in my scripts that set up my environment ... I'll look into that.  Thanks and sorry for wasting your time.
