### ISSUE TITLE
`pip install -r requirements.txt` stops on `dateutil`

### ISSUE THREAD

**Issue by bradyt** [skarra/ASynK#79]
Hi, I finally learned about `pip install -r requirements.txt`, in this next try at getting ASynK into my workflow. (Been learning a little python, yay!)

But I guess `dateutil` is not available via `pip`. I get this error: 

    (asynk)heeere-2:ASynK iam$ pip install -r requirements.txt 
    Collecting dateutil (from -r requirements.txt (line 1))
      Could not find a version that satisfies the requirement dateutil (from -r requirements.txt (line 1)) (from versions: )
    No matching distribution found for dateutil (from -r requirements.txt (line 1))

**Comment by skarra** [comment]
Hm; can you remove dateutil from the requirements.txt file? It may not be required, after all.

**Comment by bradyt** [comment]
I think that would work. I had installed the rest of list manually, and ASynK.py is working.

**Comment by bradyt** [comment]
Hmm... had a problem with dateutil with `--db cd`, googled, found `pip install python-dateutil` and it worked, so perhaps that is the correct line to add to `requirements.txt`.

**Comment by skarra** [comment]
@bradyt thanks for reporting; put that in.
